[package]
name = "lenovo-kb-lightd"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
evdev = "0.13.0"
signal-hook = "0.3.17"
nix = { version = "0.29.0", features = ["poll"] }